- code:             en
  lang:             English
  enter_phone:      Enter phone number
  text_me:          Text me
  disclosure:       It's private, secure, and built by a nonprofit.
  disclosure_link:  Learn more
  share:            Share
  tweet:            Tweet
  donate:           Donate
  powered_by:       powered by

- code:             es
  lang:             Spanish
  page_translation: false
  enter_phone:      Translated phone
  text_me:          SMS Spanish
  disclosure:       Spanish disclosure
  disclosure_link:  Spanish learn more
  share:            Share
  tweet:            Tweet
  donate:           Donate
  powered_by:       powered by
