- code:             en
  lang:             English
  enter_phone:      Enter phone number
  text_me:          Text me
  disclosure:       <a href="https://www.fightforthefuture.org/privacy/">Fight for the Future</a> & its <a href="https://fftfef.org/privacy">Education Fund</a> will contact you.
  disclosure_partner: <a href="https://www.fightforthefuture.org/privacy/">Fight for the Future</a>, its <a href="https://fftfef.org/privacy">Education Fund</a> and <a class=partner>PARTNER</a> will contact you.
  learn_more:       Learn more
  share:            Share
  tweet:            Tweet
  donate:           Donate
  powered_by:       powered by

- code:             es
  lang:             Spanish
  page_translation: false
  enter_phone:      Translated phone
  text_me:          SMS Spanish
  disclosure:       Spanish disclosure
  disclosure_link:  Spanish learn more
  share:            Share
  tweet:            Tweet
  donate:           Donate
  powered_by:       powered by
