language: node_js
node_js:
- '10'
sudo: false
cache:
  bundler: true
  directories:
  - node_modules
  - vendor
before_install:
  - if [ -f node_modules/.bin/which ]; then mv node_modules/.bin/which node_modules/.bin/which.backup; fi
  - rvm install `cat .ruby-version`
  - gem install bundler
  - if [ -f node_modules/.bin/which.backup ]; then mv node_modules/.bin/which.backup node_modules/.bin/which; fi
  - >-
    openssl aes-256-cbc
    -K $encrypted_621008db70f1_key
    -iv $encrypted_621008db70f1_iv
    -in github_deploy_key.enc
    -out github_deploy_key
    -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key
install:
  - npm install
script:
  - npm run build
after_success:
  - npm run-script deploy
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
