language: node_js
node_js:
- '4.1'
sudo: false
cache:
  bundler: true
  directories:
  - node_modules
  - vendor
before_install:
  - if [ -f node_modules/.bin/which ]; then mv node_modules/.bin/which node_modules/.bin/which.backup; fi
  - rvm install `cat .ruby-version`
  - gem install bundler
  - if [ -f node_modules/.bin/which.backup ]; then mv node_modules/.bin/which.backup node_modules/.bin/which; fi
install:
  - npm install
script:
  - npm run build
after_success:
  - npm run-script deploy
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
