#################################################
# Config: Development                           #
#################################################
# (production settings go in _config.build.yml) #

#############
# Meta info #
#############

name: 'HelloVote — Voter Registration Made Easy'
url: https://www.hellovote.org
description: Register to vote with just a few text messages!
timezone: America/New_York
googleanalytics: UA-26576645-30
petitions_api: 'https://info.fightforthefuture.org'

pathlead: '' # use this if you need a leading slash or directory on asset paths

author:
    googleid: 102356128596404327231
    twitterid: 382376904
    twitter: fightfortheftr

###########
# Content #
###########

future: true
show_drafts: true
permalink: /:title/ # See Jekyll documentation for permalink styles

defaults:
  - scope:
      type: partners
    values:
      layout: default
  - scope:
      type: partners_es
    values:
      layout: default
  - scope:
      type: partners_iframes
    values:
      layout: iframe

collections:
  partners:
    output: true
    permalink: :path/
  partners_es:
    output: true
    permalink: :path/es/
  partners_iframes:
    output: true
    permalink: :path/iframe/
  states:
    output: true
    permalink: :path/
  posts:
    output: true
    permalink: :path/
  translations:
    output: true
    permalink: :path/

#############
# Compiling #
#############

exclude: ['img']
keep_files: ['img', 'js', 'css']
gems:
  - jekyll-redirect-from
markdown: kramdown
